image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest

stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE: ebispot/eqtl-sumstats-service

build:
  stage: build
  script:
    # Login to Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin

    # Build the new image
    - docker build --network=host 
      -t $DOCKER_IMAGE:$CI_COMMIT_SHA 
      -t $DOCKER_IMAGE:latest 
      -f spark/Dockerfile .

    # Push both the SHA-tagged and latest images
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest

  only:
    - master
    - dev