image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:latest

stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_IMAGE: ebispot/eqtl-sumstats-service

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  script:
    # Login to Docker Hub
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin

    # Build the image using docker-compose
    - docker-compose build

    # Tag the built image with CI_COMMIT_SHA
    - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$CI_COMMIT_SHA

    # Push both the SHA-tagged and latest images
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest

  only:
    - master
    - dev